services:
  app:
    build: 
      context: .
      target: builder
    command: bash -c 'eval $(opam config env) && dune exec project_name'
    working_dir: /app
    deploy:
      resources:
        limits:
          cpus: "0.5"

  # dev environment
  dev:
    build:
      context: .
      target: dev
    command: tail -f /dev/null
    working_dir: /app
    volumes:
      - ./dune:/app/dune
      - ./dune-project:/app/dune-project
      - ./project_name.opam:/app/project_name.opam
      - ./main.ml:/app/main.ml